site_name: Certificate Identity Declaration SDK for Citrix Workspace app for Windows    
site_description:  Certificate Identity Declaration SDK for Citrix Workspace app for Windows
theme_dir: citrix-sdk
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      anchorlink: True

pages:
- Home: index.md
